{% set version = "0.1" %}

package:
    name: BigMPI 
    version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/jeffhammond/BigMPI/archive/v{{ version }}.tar.gz
    sha256: 237343c45fae2ca3d2f804f8d34b714b558d0e91cdcb271eb50a1fa16740666b

build:
    number: 5
    skip: True  # [win]

requirements:
    build:
        - mpich
        - gcc  # [not win]
        - toolchain
    run:
        - mpich
        - libgcc  # [linux]

test:
    requires:
        - mpich
        - gcc  # [not win]
    files:
        - tests/helloworld.c
    commands:
        - conda inspect objects bigmpi  # [osx]
        - conda inspect linkages bigmpi  # [not win]

about:
    home: https://github.com/jeffhammond/BigMPI
    license: MIT
    license_file: LICENSE
    license_family: MIT
    summary: 'Implementation of MPI that supports large counts.'
    description: |
        Implementation of MPI that supports large counts.
    doc_url: https://github.com/jeffhammond/BigMPI
    dev_url: https://github.com/jeffhammond/BigMPI

extra:
    recipe-maintainers:
        - jeffhammond
